# Generated by Django 3.0.5 on 2021-05-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_mylist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='slug',
        ),
    ]
