# Generated by Django 3.0.5 on 2021-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_mylist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
